name: Run Pytest Selenium CI

on:
  # 手動觸發：當需要執行時，手動執行 CI
  workflow_dispatch:
  # 自動觸發：當有 push 時，自動觸發 CI
  # push:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser fonts-liberation libnss3 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libx11-xcb1 libgbm-dev

      - name: Run Pytest
        run: |
          pytest test_cicd.py -v