name: Run Pytest Selenium CI

on:
  # 手動觸發
  workflow_dispatch:
  # 自動觸發
  # push:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium chromium-driver fonts-liberation \
              libnss3 libxss1 libatk-bridge2.0-0 libgtk-3-0 libx11-xcb1 libgbm-dev libasound2-data

      - name: Run Pytest
        run: |
          pytest test_cicd.py -v